# Generated by Django 4.1.4 on 2022-12-28 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confTopic', models.CharField(choices=[('0', 'مهندسی و علوم فیزیکی'), ('1', 'کشاورزی و علوم زیستی'), ('2', 'پزشکی'), ('3', 'علوم انسانی')], max_length=1, verbose_name='موضوع کنفرانس')),
                ('confType', models.CharField(choices=[('0', 'منطقه ای'), ('1', 'ملی'), ('2', 'بین المللی')], max_length=500, verbose_name='نوع کنفرانس')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان کنفرانس')),
                ('event_date', models.DateField(verbose_name='تاریخ برگزاری')),
                ('event_place', models.CharField(max_length=500, verbose_name='محل برگزاری')),
            ],
            options={
                'verbose_name': 'کنفرانس',
                'verbose_name_plural': 'کنفرانس ها',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journalType', models.CharField(choices=[('0', 'داخلی'), ('1', 'خارجی')], max_length=1, verbose_name='نوع ژورنال')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان ژورنال')),
                ('issn', models.CharField(max_length=500, verbose_name='شابک')),
                ('volume', models.CharField(max_length=500, verbose_name='شمارگان ژورنال')),
                ('publisher', models.CharField(max_length=500, verbose_name='ناشر')),
                ('rank', models.CharField(max_length=500, verbose_name='رتبه ژورنال')),
            ],
            options={
                'verbose_name': 'ژورنال',
                'verbose_name_plural': 'ژورنال ها',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperType', models.CharField(choices=[('0', 'ژورنال داخلی'), ('1', 'ژورنال خارجی'), ('2', 'کنفرانس داخلی'), ('3', 'کنفرانس خارجی')], max_length=1, verbose_name='نوع مقاله')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان مقاله')),
                ('doi', models.CharField(max_length=1000)),
                ('author1', models.CharField(max_length=500, verbose_name='نویسنده اول')),
                ('author2', models.CharField(max_length=500, verbose_name='نویسنده دوم')),
                ('author3', models.CharField(max_length=500, verbose_name='نویسنده سوم')),
                ('author4', models.CharField(max_length=500, verbose_name='نویسنده چهارم')),
                ('abstract', models.TextField(verbose_name='چکیده مقاله')),
                ('volume', models.CharField(max_length=500, verbose_name='شمارگان ژورنال')),
                ('publication_date', models.DateField(verbose_name='تاریخ انتشار')),
                ('paper_image', models.ImageField(blank=True, null=True, upload_to='paperImages/', verbose_name='تصویر مقاله')),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='researchActivities.conference', verbose_name='کنفرانس')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='researchActivities.journal', verbose_name='ژورنال')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله ها',
            },
        ),
    ]
