# Generated by Django 4.1.4 on 2023-03-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchActivities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pdfjournal',
            field=models.FileField(blank=True, null=True, upload_to='pdf/', verbose_name='pdf مقاله'),
        ),
    ]
