# Generated by Django 4.1.4 on 2023-03-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchActivities', '0002_paper_pdfjournal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jozveh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('prof', models.CharField(max_length=150, verbose_name='نام استاد')),
                ('pdfjozveh', models.FileField(blank=True, null=True, upload_to='pdfjozveh/', verbose_name='pdf جزوه')),
                ('jozveh_image', models.ImageField(blank=True, null=True, upload_to='jozvehImages/', verbose_name='تصویر جزوه')),
            ],
            options={
                'verbose_name': 'جزوه ها',
                'verbose_name_plural': 'جزوه ها',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('pdfpresentation', models.FileField(blank=True, null=True, upload_to='pdfPresentation/', verbose_name='pdf ارائه')),
                ('presentation_image', models.ImageField(blank=True, null=True, upload_to='presentationImages/', verbose_name='تصویر ارائه')),
            ],
            options={
                'verbose_name': 'ارائه ها',
                'verbose_name_plural': 'ارائه ها',
            },
        ),
    ]
