# Generated by Django 4.1.4 on 2023-03-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biography',
            options={'verbose_name': 'بیوگرافی', 'verbose_name_plural': 'بیوگرافی'},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'علاقه مندی ها', 'verbose_name_plural': 'علاقه مندی ها'},
        ),
    ]
