# Generated by Django 4.1.4 on 2023-03-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_alter_biography_options_alter_favorites_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='projectImages/', verbose_name='تصویر نمونه کار')),
            ],
            options={
                'verbose_name': 'نمونه کارها',
                'verbose_name_plural': 'نمونه کارها',
            },
        ),
    ]
